# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_finger_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_left_inner_finger_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_left_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_right_inner_finger_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_right_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_right_outer_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 2
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder_lift_joint:
    min_position: -2.94
    max_position: -0.2
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: false
    max_acceleration: 0
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: false
    max_acceleration: 0
  wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: false
    max_acceleration: 0
